<?php

namespace ContainerGJSfoAs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RpRiR2JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RpRiR2J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RpRiR2J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
