<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAwgeAJQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAwgeAJQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAwgeAJQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAwgeAJQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAwgeAJQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'AwgeAJQ',
    'container.build_id' => '8f48f9f1',
    'container.build_time' => 1676312159,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAwgeAJQ');
